name: metronome
description: Efficient, accurate, cross-platform metronome with professional features
version: 1.1.5

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  path_provider: ^2.1.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true